services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: front-end
    ports:
      - "9000"
    depends_on:
      back-end:
        condition: service_started

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: back-end
    ports:
      - "5252"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5252

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    ports:
      - "80:80"
    depends_on:
      front-end:
        condition: service_started
      back-end:
        condition: service_started
